export type Client =
  | {
      name: string;
      industry: string;
      logo: string;
    }
  | {
      name: string;
      industry: string;
      logo?: undefined;
    };

export const clientIndustries = [
  "Manufacturing",
  "Automotive",
  "Defence & Aerospace",
  "Electronics",
  "Oil & Gas",
  "Others",
] as const;

export const clients: Client[] = [
  { name: "Anabond", industry: "Manufacturing", logo: "/client_list/Manufacturing/Anabond.png" },
  { name: "Belrise", industry: "Manufacturing", logo: "/client_list/Manufacturing/BelriseManufacture.png" },
  { name: "Bhushan Steel", industry: "Manufacturing", logo: "/client_list/Manufacturing/bhushan.png" },
  { name: "BMT", industry: "Manufacturing", logo: "/client_list/Manufacturing/BMTManufacture.png" },
  { name: "Carro India", industry: "Manufacturing", logo: "/client_list/Manufacturing/Carro-IndiaManufacture.png" },
  { name: "Cummins", industry: "Manufacturing", logo: "/client_list/Manufacturing/CumminsManufacture.png" },
  { name: "Dow", industry: "Manufacturing", logo: "/client_list/Manufacturing/DowManufacture.png" },
  { name: "Endurance", industry: "Manufacturing", logo: "/client_list/Manufacturing/EnduranceManufacture.png" },
  { name: "Escort", industry: "Manufacturing", logo: "/client_list/Manufacturing/Escort-Manufacture-1.png" },
  { name: "Fleet Gaurd", industry: "Manufacturing", logo: "/client_list/Manufacturing/FleetGaurdManufacture.png" },
  { name: "General Motors", industry: "Manufacturing", logo: "/client_list/Manufacturing/General-MotorsManufacture.png" },
  { name: "Global Eng", industry: "Manufacturing", logo: "/client_list/Manufacturing/GlobalEngManufacture.png" },
  { name: "GM", industry: "Manufacturing", logo: "/client_list/Manufacturing/GMManufacture.png" },
  { name: "Granite", industry: "Manufacturing", logo: "/client_list/Manufacturing/GraniteManufacture.png" },
  { name: "GSK", industry: "Manufacturing", logo: "/client_list/Manufacturing/GSKManufacture.png" },
  { name: "Jindal", industry: "Manufacturing", logo: "/client_list/Manufacturing/Jindal New Logo (1).jpg" },
  { name: "Josts", industry: "Manufacturing", logo: "/client_list/Manufacturing/JostsManufacture.png" },
  { name: "Leo", industry: "Manufacturing", logo: "/client_list/Manufacturing/LeoManufacture.png" },
  { name: "Lumax", industry: "Manufacturing", logo: "/client_list/Manufacturing/LumaxManufacture.png" },
  { name: "MSL", industry: "Manufacturing", logo: "/client_list/Manufacturing/MSLManufacture.png" },
  { name: "Reliance", industry: "Manufacturing", logo: "/client_list/Manufacturing/Reliance-Manufacture.png" },
  { name: "Sivshakti Engineering", industry: "Manufacturing" },
  { name: "Spicer", industry: "Manufacturing", logo: "/client_list/Manufacturing/SpicerManufacture.png" },
  { name: "Swathi Eng", industry: "Manufacturing", logo: "/client_list/Manufacturing/SwathiEngManufacture.png" },
  { name: "Tata Metaliks", industry: "Manufacturing", logo: "/client_list/Manufacturing/Tata-Metaliks-1.png" },
  { name: "Tata Steel", industry: "Manufacturing", logo: "/client_list/Manufacturing/tata-steel.png" },
  { name: "Tech Steel", industry: "Manufacturing", logo: "/client_list/Manufacturing/tech-steel.png" },
  { name: "TMTL", industry: "Manufacturing", logo: "/client_list/Manufacturing/TMTLManufacture.png" },
  { name: "Toyota", industry: "Manufacturing", logo: "/client_list/Manufacturing/Toyota.png" },
  { name: "Varroc", industry: "Manufacturing", logo: "/client_list/Manufacturing/VarrocManufacture.png" },
  { name: "Volvo", industry: "Manufacturing", logo: "/client_list/Manufacturing/VolvoManufacture.png" },
  { name: "Welspun Corp", industry: "Manufacturing", logo: "/client_list/Manufacturing/WelspunCorp.png" },
  { name: "ZF India", industry: "Manufacturing", logo: "/client_list/Manufacturing/ZF-IndiaManufacture.png" },
  { name: "Ashok Leyland", industry: "Automotive", logo: "/client_list/Automotive/Ashok-Leyland.png" },
  { name: "Bajaj", industry: "Automotive", logo: "/client_list/Automotive/BajajAutomotive.png" },
  { name: "Daimler Chrysler (Mercedes Benz)", industry: "Automotive", logo: "/client_list/Automotive/Daimler-Chrysler.png" },
  { name: "Eicher", industry: "Automotive", logo: "/client_list/Automotive/EicherAutomotive.png" },
  { name: "Farmtrac", industry: "Automotive", logo: "/client_list/Automotive/Farmtrac.png" },
  { name: "Fiat", industry: "Automotive", logo: "/client_list/Automotive/FiatAutomotive.png" },
  { name: "Ford Motors", industry: "Automotive", logo: "/client_list/Automotive/Ford.png" },
  { name: "General Motors", industry: "Automotive", logo: "/client_list/Automotive/General-Motors.png" },
  { name: "Godrej Boyce", industry: "Automotive", logo: "/client_list/Automotive/Godrej-Boyce.png" },
  { name: "Honda", industry: "Automotive", logo: "/client_list/Automotive/HondaAutomotive.png" },
  { name: "Honda Siel Cars", industry: "Automotive", logo: "/client_list/Automotive/HondaAutomotive-1.png" },
  { name: "Hyundai Motors", industry: "Automotive", logo: "/client_list/Automotive/Hyundai.png" },
  { name: "ISMT Ltd.", industry: "Automotive" },
  { name: "LT", industry: "Automotive", logo: "/client_list/Automotive/LTAutomotive.png" },
  { name: "Mahindra & Mahindra", industry: "Automotive", logo: "/client_list/Automotive/Mahindra.png" },
  { name: "Mercedes", industry: "Automotive", logo: "/client_list/Automotive/MercedesAutomotive.png" },
  { name: "Piaggio", industry: "Automotive", logo: "/client_list/Automotive/Piaggio.png" },
  { name: "Surin", industry: "Automotive", logo: "/client_list/Automotive/SurinAutomotive.png" },
  { name: "TATA", industry: "Automotive", logo: "/client_list/Automotive/TATAAutomotive.png" },
  { name: "Tata Motors", industry: "Automotive", logo: "/client_list/Automotive/Tata-Motors.png" },
  { name: "Toyota Kirloskar", industry: "Automotive", logo: "/client_list/Automotive/Toyota.png" },
  { name: "Volkswagen", industry: "Automotive", logo: "/client_list/Automotive/Vw.png" },
  { name: "Army", industry: "Defence & Aerospace", logo: "/client_list/Defence & Aerospace/ArmyDefence.png" },
  { name: "BSL", industry: "Defence & Aerospace", logo: "/client_list/Defence & Aerospace/BSLShipyard.png" },
  { name: "DDefence", industry: "Defence & Aerospace", logo: "/client_list/Defence & Aerospace/DDefence.png" },
  { name: "Defence", industry: "Defence & Aerospace", logo: "/client_list/Defence & Aerospace/Defence-Shipyard.png" },
  { name: "Defence Factory", industry: "Defence & Aerospace", logo: "/client_list/Defence & Aerospace/Defence-FactoryDefence.png" },
  { name: "DRDO", industry: "Defence & Aerospace", logo: "/client_list/Defence & Aerospace/DRDODefence.png" },
  { name: "Indian Army", industry: "Defence & Aerospace", logo: "/client_list/Defence & Aerospace/Indian-ArmyDefence.png" },
  { name: "ISRO", industry: "Defence & Aerospace", logo: "/client_list/Defence & Aerospace/ISRODefence.png" },
  { name: "ABB", industry: "Electronics", logo: "/client_list/Electronics/ABBElectro.png" },
  { name: "BHEL", industry: "Electronics", logo: "/client_list/Electronics/BHELElectronics.png" },
  { name: "Electrosteel", industry: "Electronics", logo: "/client_list/Electronics/Electrosteel-1.png" },
  { name: "GKC", industry: "Electronics", logo: "/client_list/Electronics/GKC.png" },
  { name: "Havells", industry: "Electronics", logo: "/client_list/Electronics/HavellsElectro.png" },
  { name: "Twin Engineers", industry: "Electronics", logo: "/client_list/Electronics/Twin-EngineersElectro.png" },
  { name: "Zauba Corp", industry: "Electronics", logo: "/client_list/Electronics/ZaubaCorpElectro.png" },
  { name: "Al Jazeera Steel Products (Oman)", industry: "Oil & Gas", logo: "/client_list/Oil & Gas/jazeera.png" },
  { name: "Balmer Lawrie & Co. Ltd.", industry: "Oil & Gas", logo: "/client_list/Oil & Gas/b-L.png" },
  { name: "Conares (UAE)", industry: "Oil & Gas", logo: "/client_list/Oil & Gas/conares.png" },
  { name: "Indian Oil Corporation (IOC)", industry: "Oil & Gas", logo: "/client_list/Oil & Gas/indian-oil.png" },
  { name: "Maharashtra Seamless Ltd.", industry: "Oil & Gas", logo: "/client_list/Oil & Gas/msl.png" },
  { name: "Man Industries Ltd.", industry: "Oil & Gas", logo: "/client_list/Oil & Gas/man.png" },
  { name: "PSL Ltd.", industry: "Oil & Gas", logo: "/client_list/Oil & Gas/psl.png" },
  { name: "Welspun Corp Ltd.", industry: "Oil & Gas", logo: "/client_list/Oil & Gas/welspun-corp.png" },
  { name: "Ace Construction", industry: "Others", logo: "/client_list/Others/Ace-Construction.png" },
  { name: "Anwesha Packaging", industry: "Others", logo: "/client_list/Others/AnweshaPackaging.png" },
  { name: "APL Apollo", industry: "Others", logo: "/client_list/Others/Aplapollo.png" },
  { name: "Balmer Packaging", industry: "Others", logo: "/client_list/Others/BalmerPackaging.png" },
  { name: "Cetury Barrel", industry: "Others" },
  { name: "Cracker Barrel", industry: "Others", logo: "/client_list/Others/Cracker-Barrel.png" },
  { name: "DB", industry: "Others", logo: "/client_list/Others/DB-1.png" },
  { name: "Diti Resource Pvt. Ltd.", industry: "Others" },
  { name: "DM Resources", industry: "Others", logo: "/client_list/Others/DM_Resources.png" },
  { name: "Electrosteel Castings Ltd.", industry: "Others", logo: "/client_list/Others/Electrosteel.png" },
  { name: "Essar", industry: "Others", logo: "/client_list/Others/Essar.png" },
  { name: "GCL", industry: "Others", logo: "/client_list/Others/Gcl.png" },
  { name: "Genix Automation", industry: "Others", logo: "/client_list/Others/genix-automation.png" },
  { name: "Gujarat Container Ltd.", industry: "Others" },
  { name: "Hazira Pipe Mill Ltd.", industry: "Others" },
  { name: "Insider Biz", industry: "Others", logo: "/client_list/Others/InsiderBiz.png" },
  { name: "Jindal Saw Ltd.", industry: "Others" },
  { name: "JSL", industry: "Others", logo: "/client_list/Others/JSL.png" },
  { name: "Kumar Container Pvt. Ltd.", industry: "Others", logo: "/client_list/Others/Kumar Containers Pvt. Ltd..png" },
  { name: "Megha Engineering & Infrastructure Ltd. (MEIL)", industry: "Others", logo: "/client_list/Others/Meil-1.png" },
  { name: "MM Barrel", industry: "Others", logo: "/client_list/Others/MM BARELS Logo.webp" },
  { name: "Movers and Equipments", industry: "Others", logo: "/client_list/Others/Movers-and-Equipments.png" },
  { name: "PARI Automation", industry: "Others", logo: "/client_list/Others/PARI-Automation.png" },
  { name: "Railway", industry: "Others", logo: "/client_list/Others/Railway.png" },
  { name: "Ratnamani Metals & Tubes Ltd.", industry: "Others", logo: "/client_list/Others/Ratnamani.png" },
  { name: "Royal Industrie", industry: "Others" },
  { name: "Shipyard", industry: "Others", logo: "/client_list/Others/Shipyard-3.png" },
  { name: "Siva Ram Barrel Industries", industry: "Others", logo: "/client_list/Others/Siva Ram Barrel Industries Logo.webp" },
  { name: "Surya Roshni Ltd.", industry: "Others", logo: "/client_list/Others/Surya.png" },
  { name: "Vinora Industrie", industry: "Others" },
  { name: "WMI", industry: "Others", logo: "/client_list/Others/WMI.png" },
];

export const clientsByIndustry = clientIndustries.reduce((acc, ind) => {
  acc[ind] = clients.filter((c) => c.industry === ind);
  return acc;
}, {} as Record<(typeof clientIndustries)[number], Client[]>);
