CATALOGUE_AUTHORITY_PRIORITY = 100
COMPANY_AUTHORITY_PRIORITY = 90
SUPPORTING_AUTHORITY_PRIORITY = 80

SOURCE_TYPE_CATALOGUE = "catalogue"
SOURCE_TYPE_COMPANY_MASTER = "company_master"
SOURCE_TYPE_CERTIFICATE = "certificate"
SOURCE_TYPE_OTHER = "other"

STATUS_PENDING = "pending"
STATUS_PROCESSING = "processing"
STATUS_INDEXED = "indexed"
STATUS_FAILED = "failed"
STATUS_OUTDATED = "outdated"

CHUNK_TYPE_PRODUCT_IDENTITY = "product_identity"
CHUNK_TYPE_DESCRIPTION = "description"
CHUNK_TYPE_FEATURES = "features"
CHUNK_TYPE_APPLICATIONS = "applications"
CHUNK_TYPE_TECHNICAL_MODEL = "technical_model"
CHUNK_TYPE_TECHNICAL_TABLE = "technical_table"
CHUNK_TYPE_TECHNICAL_VARIANT = "technical_variant"
CHUNK_TYPE_TECHNICAL_PART = "technical_part"
CHUNK_TYPE_TECHNICAL_SPECIFICATIONS = "technical_specifications"
CHUNK_TYPE_SYSTEM_COMPONENT = "system_component"
CHUNK_TYPE_SYSTEM_WORKFLOW = "system_workflow"
CHUNK_TYPE_SYSTEM_COMPARISON = "system_comparison"
CHUNK_TYPE_ACCESSORIES = "accessories"
CHUNK_TYPE_NOTES = "notes"
CHUNK_TYPE_OTHER = "other"
CHUNK_TYPE_PRODUCT_MASTER = "product_master"
CHUNK_TYPE_SECTION = "section"
CHUNK_TYPE_CONTACT = "contact"

DATA_STATUS_VR_VERIFIED = "VR VERIFIED"
DATA_STATUS_EXTERNALLY_VERIFIED = "EXTERNALLY VERIFIED"
DATA_STATUS_DERIVED = "DERIVED"
DATA_STATUS_INFERRED = "INFERRED"
DATA_STATUS_PROPOSED = "PROPOSED"
DATA_STATUS_UNKNOWN_TBC = "UNKNOWN / TBC"
DATA_STATUS_CONFLICT = "CONFLICT"

CONTENT_TYPE_TECHNICAL_MODEL = "technical_model"
CONTENT_TYPE_TECHNICAL_TABLE = "technical_table"

VERIFICATION_STATUSES = {
    DATA_STATUS_VR_VERIFIED,
    DATA_STATUS_EXTERNALLY_VERIFIED,
    DATA_STATUS_DERIVED,
    DATA_STATUS_INFERRED,
    DATA_STATUS_PROPOSED,
    DATA_STATUS_UNKNOWN_TBC,
    DATA_STATUS_CONFLICT,
}
